# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-11-26T06:09:08+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, conint


class MenuItem(BaseModel):
    id: str
    name: str
    price: float


class OrderItem(BaseModel):
    menu_item_id: str
    quantity: conint(ge=1)


class Order(BaseModel):
    items: List[OrderItem]


class LineItem(BaseModel):
    name: str
    quantity: int
    unit_price: float
    subtotal: float


class Receipt(BaseModel):
    line_items: List[LineItem]
    subtotal: float
    tax: float
    total: float
