# docker-compose.yml
version: "3.7"
services:
  app:
    build:
      args:
        user: ${USER}
        uid: ${USER_UID}
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./:/home/${USER}/server
    networks:
      - server-network
    env_file: .env
    environment:
      - USER
networks:
  server-network:
    driver: bridge
