# Generated by Django 4.0.5 on 2022-06-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='shortened',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
