# Algorithm
ALGORITHM_NAME = 'MergeSort'
ALGORITHM = ALGORITHM_NAME + '()'

# Screen
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 900
SCREEN_DIMENSIONS = (SCREEN_WIDTH, SCREEN_HEIGHT)
BASELINE = 100
SIDELINE = 25

# Rects
RECT_WIDTH = 1
SPACING_SIZE = 2

# Colours
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BACKGROUND = WHITE

# Styling
RANDOM = False
GRAY = False
CONSTANT = True

# Values
LENGTH = 2**9
MAX_VALUE = 2**9

# Time
TIME_SLEEP = 0
TIME_WAIT = 5000

# Logging
CONSOLE_OUTPUT = False

# Errors
ALGORITHM_NOT_FOUND = '\nThe algorithm "{}" is not available.'.format(ALGORITHM_NAME)